### ISSUE TITLE
Network Error on ROS Kinetic - Cannot preparing team's system

### ISSUE THREAD

**Issue by TuZZiX** [osrf/ariac-docker#14]
Looks like there is some network issue with preparing workspace for ROS kinetic, cannot fetch anything from the Internet.

Host system: Ubuntu 16.04 + ROS Kinetic
Using team config: [link](https://github.com/cwru-robotics/cwru_ariac/tree/master/final_submission/team_case_kinetic)

Error log:
```
Step 4/9 : RUN /build_team_system.bash
 ---> Running in fc1180552e36
Preparing environmen for running cwru_ariac
Err:1 http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial InRelease
  Temporary failure resolving 'packages.osrfoundation.org'
Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://packages.ros.org/ros/ubuntu xenial InRelease
  Temporary failure resolving 'packages.ros.org'
Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 http://archive.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/xenial/InRelease  Temporary failure resolving 'packages.osrfoundation.org'
W: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'packages.ros.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ros-kinetic-trac-ik*
E: Couldn't find any package by glob 'ros-kinetic-trac-ik*'
E: Couldn't find any package by regex 'ros-kinetic-trac-ik*'
Cloning into 'cwru_ariac'...
fatal: unable to access 'https://github.com/cwru-robotics/cwru_ariac.git/': Could not resolve host: github.com
Cloning into 'catkin_simple'...
fatal: unable to access 'https://github.com/catkin/catkin_simple.git/': Could not resolve host: github.com

```

**Comment by dhood** [comment]
Could you please try [these steps](https://stackoverflow.com/a/24991137) and see if it makes a difference? Please don't run the `./prepare_team_system.bash` script with the `--use-cache` option.

**Comment by TuZZiX** [comment]
Thanks for the help,
I tried the solution and the same issue still exists. I have also tried ROS Indigo, it gives me the same error. I think it is some problem related to Docker's network setting.

**Comment by j-rivero** [comment]
I was able to run your setup file with no problem in my home computer. Let's try to get a bit more of information to debug. Which is host your operative system and version? 

In your host machine, could you please run and paste the output of:

```
ifconfig
sysctl net.ipv4.conf.all.forwarding
docker inspect <fc1180552e36> (or the corresponding id generated during the build)
```

Give a look at `journalctl -u docker.service` just after running the prepare command, there should be something interesting there.

One more thing, could you please change your `build_team_system.bash`  by:

```
#!/usr/bin/env bash

echo "Display resolv.conf"
cat /etc/resolv.conf

echo "Try using directly the IP"
curl 140.211.166.202

echo "Try to resolv the domain name"
curl www.debian.org
```

and run the command again. Let's see if it is a problem with DNS or affecting the whole network.
Thanks.

**Comment by TuZZiX** [comment]
In the container, pinging directly using IP works but not with the domain name.

I think this can be some issue related to the network environment, the one that not working is managed under domain.

**Comment by j-rivero** [comment]
What do you have in the /etc/resolv.conf file inside the container?

**Comment by TuZZiX** [comment]
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
search ra-int.com
nameserver 8.8.4.4
nameserver 8.8.8.8
```

**Comment by j-rivero** [comment]
this looks ok to me, you will need to debug what's going on with your DNS resolution inside your network.
