### ISSUE TITLE
Support kinetic in addition to indigo

### ISSUE THREAD

**Issue by dhood** [osrf/ariac-docker#2]

**Comment by j-rivero** [comment]
I think that changes needed to run kinetic or indigo are mostly ready in the `kinetic_version` branch. The branch was made from the current pull request #6. These are the [current changes from one to another](https://github.com/osrf/ariac-docker/compare/batch_runs...kinetic_version).

I've implemented a testing script to be sure that all the images are built correctly. This run was buillding all the [ariac-server images](https://build.osrfoundation.org/view/All/job/ariac-install-docker_kinetic-xenial-amd64/11/console) just calling the `prepare_ariac_system` and after it the competitor image calling `prepare_team_system` script. Hopefully we can implement a runtime test in the near future.
